[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
odrive-rs = "1.1.0"
serde_json = "1.0.48"
nalgebra = "0.31.3"